# Generated by Django 3.2.5 on 2021-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=64)),
                ('tytul', models.CharField(max_length=64, unique=True)),
                ('kategoria', models.CharField(max_length=64)),
                ('rok', models.PositiveSmallIntegerField(default=2000)),
                ('opis', models.TextField(default='')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
            ],
        ),
    ]
