# Generated by Django 3.2.5 on 2021-07-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ksiazki',
            new_name='Ksiazka',
        ),
    ]
