# Generated by Django 3.2.5 on 2021-07-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KI', '0002_rename_ksiazki_ksiazka'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ksiazka',
            new_name='Book',
        ),
    ]
